### ISSUE TITLE
documentation syntax error

### ISSUE THREAD

**Issue by muteesa** [signalwire/signalwire-dotnet#14]
there is an extra closing bracket in the example code below which needs to be removed. 
`using SignalWire.Relay; https://docs.signalwire.com/topics/relay-sdk-dotnet/#relay-sdk-for-c-net-installation 
Client client = new Client("example.signalwire.com",
                           "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
                           "PTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"));`

**Comment by Astaelan** [comment]
Fixed in next release of docs.
