### ISSUE TITLE
create call code giving errors

### ISSUE THREAD

**Issue by muteesa** [signalwire/signalwire-dotnet#15]
this code complains about PhoneCall with error. `Program.cs(32,1): error CS0246: The type or namespace name 'PhoneCall' could not be found (are you missing a using directive or an assembly reference?)` Shane recomended adding `using SignalWire.Relay.Calling;`

`PhoneCall call = client.Calling.NewPhoneCall("+15551234567", "+15551237654");
                // Assign event callbacks
                call.Begin();
`
docs need to be updated.

**Comment by Astaelan** [comment]
Resolved in the latest docs, example is better.
