### ISSUE TITLE
Message examples for C#/.NET

### ISSUE THREAD

**Issue by joshebosh** [signalwire/signalwire-dotnet#77]
I see there are only Calling exmples present in repo.. And managed to makes calls with them...
But my shortcoming is I'm only able to manilpulate existing examples...
I'm unable to create complete examples from scratch based on dev docs alone...

Would it be possible to have two Messages examples?

One to handle incoming SMS.
One to send outgoing SMS.

Thanks for any help on this

**Comment by joshebosh** [comment]
Shashi (mostly Shashi) and I managed to create an incoming example that auto replies to "Help" keyword

```
using System;
using SignalWire.Relay;
using SignalWire.Relay.Messaging;
using System.Collections.Generic;

namespace Message_Inbound
{
    internal class ExampleConsumer : Consumer
    {
        protected override void Setup()
        {
            Project = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
            Token = "PTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            Contexts = new List<string> { "myContext" };
        }

        protected override void OnIncomingMessage(Message message)
        {
            base.OnIncomingMessage(message);
            Console.WriteLine(message.Body);
            Console.WriteLine(message.To);
            Console.WriteLine(message.From);
            //Console.ReadLine();

            if (message.Body == "Help") {
                SendResult resultSend = Client.Messaging.Send("joshebosh", message.From, message.To, new SendSource("My Test Message"));
                if (resultSend.Successful)
                {
                    // Message has been queued, you can subscribe to MessagingAPI.OnMessageStateChange to receive further updates
                }
            }
        }
    }

    internal class Program
    {
        public static void Main()
        {
            new ExampleConsumer().Run();
        }
    }
}
```

**Comment by joshebosh** [comment]
and a simple outbound message example

```
using System;
using SignalWire.Relay;
using SignalWire.Relay.Messaging;
//using SignalWire.Relay.Messaging.SendSource;
using System.Collections.Generic;

namespace Message_Outbound
{
    internal class ExampleConsumer : Consumer
    {
        protected override void Setup()
        {
            Project = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
            Token = "PTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }

        protected override void Ready()
        {

                SendResult resultSend = Client.Messaging.Send("joshebosh", "+1931XXXXXXX", "+1334XXXXXXX", new SendSource("My Test Message"));
            if (resultSend.Successful)
            {
                // Message has been queued, you can subscribe to MessagingAPI.OnMessageStateChange to receive further updates
            }
        }
    }

    internal class Program
    {
        public static void Main()
        {
            new ExampleConsumer().Run();
        }
    }
}
```

**Comment by joshebosh** [comment]
hopefully that'll help others with .NET message examples

**Comment by Astaelan** [comment]
Great job guys, I think we can close this ticket then if you don't need any further assistance.

**Comment by ejbiker93ss** [comment]
Hi!

I have used your example to successfully receive messages, but sending doesn't seem to work. Has something possibly changed since this was posted?

**Comment by Astaelan** [comment]
> Hi!
> 
> I have used your example to successfully receive messages, but sending doesn't seem to work. Has something possibly changed since this was posted?

Make sure you're using the latest nuget package of signalwire-dotnet, there has been some changes that are reflected in the packages but NOT in this source repository, the current latest source repository for public use is at https://github.com/signalwire/signalwire-dotnet-lite if you need the source.

While I'm not exactly sure which version you're using if you are using an older version, most of the changes were internal and the public interfaces did not significantly change, particularly around the Messaging API.  So the examples should work.

Add the following to the top of the `Program.Main` function to enable deeper log output and then include a copy of the output during a failed Send.
```SignalWireLogging.LoggerFactory.AddSimpleConsole(LogLevel.Trace);```

Also, as a final consideration, it may be required to setup a verified campaign due to the changes around SMS/MMS for sending with carriers, but I am not well versed in the specific limits or legal requirements.

**Comment by ejbiker93ss** [comment]
I think my problem may be that I don't have a campaign set up. It looks like that process isn't very easy anymore, which is good

**Comment by Astaelan** [comment]
> So my code is working now. I guess my campaign wasn't approved yet. It's a shame that you have to go through so many hoops to even send a few messages to test my application 😦

Glad you got it figured out, I'm sure over time the campaign registry will improve and streamline the process.

**Comment by emok93** [comment]
Wouldn't it make sense to allow, say 1 message per minute with a total of 10 messages per hour, for people like me who are just testing things to see if I want to go with SignalWire or not?

**Comment by Astaelan** [comment]
To my knowledge this is controlled by the carriers who decide whether or not to allow the messages, which in turn is I believe controlled by compliance with the FCC mandates.  This isn't really within our control, but really a federal compliance.  If you would like to know more about the campaigns I'm sure our support team would be happy to fill in any of the details with much better information than I can provide.

**Comment by emok93** [comment]
Thanks @Astaelan

**Comment by ejbiker93ss** [comment]
Hello!

Any ideas what might cause my `protected override void OnIncomingMessage(Message message)` to fire twice? It doesn't do it at first, but after my app has been running for a few hours, it starts doing it.

**Comment by Astaelan** [comment]
Please contact support so they can investigate and confirm the source of the issue.

**Comment by LuvForAirplanes** [comment]
> Hello!
> 
> Any ideas what might cause my `protected override void OnIncomingMessage(Message message)` to fire twice? It doesn't do it at first, but after my app has been running for a few hours, it starts doing it.

@ejbiker93ss Did you ever figure out why this was happening? I have the same issues occasionally!

**Comment by ejbiker93ss** [comment]
I never did figure it out. I ended up just storing the last recipient and message to a variable, then making sure I don't send out the same message twice
